- name: gp
  configMap:
    name: gpfmxmsg
- name: dumps
  persistentVolumeClaim:
    claimName: hcdumps
- name: fmx
  persistentVolumeClaim:
    claimName: fmx
- name: data
  persistentVolumeClaim:
    claimName: data
- name: amos
  persistentVolumeClaim:
    claimName: amos

